import { SearchResponse } from '@features/dashboard/models/search.model';

export const MOCK_SEARCH_RESPONSE: SearchResponse = {
  success: true,
  message: 'Mock search response',
  timestamp: '2026-02-28T08:42:40.680721+00:00',
  data: {
    search_id: '69a2aa803dd151790b5a4d25',
    phone: '+919997260627',
    country_code: '+91',
    status: 'completed',
    results_count: 7,
    failed_count: 4,
    error_message: '4 sources failed',
    created_at: '2026-02-28T08:42:40.680721+00:00',
    updated_at: '2026-02-28T08:42:40.680769+00:00',
    results: [
      {
        source: 'viewcaller',
        type: 'name',
        value: 'Anshul Saxena',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'viewcaller',
        type: 'name',
        value: 'Anshul CTO',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'name',
        value: 'Anshul Saxena',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'birthday',
        value: '1994-07-28',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'gender',
        value: 'MALE',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'image',
        value:
          'https://images-noneu.truecallerstatic.com/myview/1/470040438f8d5c04db06efd68391dfa8/1',
        sourceOrType: 'type',
        category: 'IMAGE',
      },
      {
        source: 'truecaller',
        type: 'carrier',
        value: 'Airtel',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'phone_type',
        value: 'openPhone',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'phone_type',
        value: 'MOBILE',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'address',
        value: 'Not Available',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'email',
        value: 'anshulsaxena2807@gmail.com',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'internetAddress',
        value: 'anshulsaxena2807@gmail.com',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'badge',
        value: 'user',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'badge',
        value: 'verified',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'truecaller',
        type: 'badge',
        value: 'premium',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'eyecon',
        type: 'name',
        value: 'Anshul Saxena',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'eyecon',
        type: 'image',
        value: 'Not Available',
        sourceOrType: 'type',
        category: 'IMAGE',
      },
      {
        source: 'eyecon',
        type: 'name',
        value: 'Anshul Saxena Grossint',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'eyecon',
        type: 'name',
        value: 'Anshul CTO',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'eyecon',
        type: 'name',
        value: 'Anshul My Son',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'eyecon',
        type: 'facebook',
        value: 'Not Available',
        sourceOrType: 'type',
        category: 'LINK',
      },
      {
        source: 'eyecon',
        type: 'image',
        value: 'Not Available',
        sourceOrType: 'type',
        category: 'IMAGE',
      },
      {
        source: 'callapp',
        type: 'name',
        value: 'anshul cto',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'Account Exist',
        type: 'whatsapp',
        value: 'Yes',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Phone Number',
        type: 'whatsapp',
        value: '+91 99972 60627',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Country Code',
        type: 'whatsapp',
        value: 'IN',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'About',
        type: 'whatsapp',
        value: 'Not Available',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'About Set At',
        type: 'whatsapp',
        value: 'Not Available',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Last Seen',
        type: 'whatsapp',
        value: '2026-02-28T08:41:39.650Z',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'WhatsApp ID',
        type: 'whatsapp',
        value: '919997260627@c.us',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'whatsapp',
        type: 'image',
        value: 'Not Available',
        sourceOrType: 'type',
        category: 'IMAGE',
      },
      {
        source: 'Verified',
        type: 'whatsapp',
        value: 'No',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Business Account',
        type: 'whatsapp',
        value: 'No',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Is User',
        type: 'whatsapp',
        value: 'Yes',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Is WhatsApp Contact',
        type: 'whatsapp',
        value: 'Yes',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Is Blocked',
        type: 'whatsapp',
        value: 'No',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Enterprise Account',
        type: 'whatsapp',
        value: 'No',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Image Description',
        type: 'whatsapp',
        value: 'Not Available',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Image Tag',
        type: 'whatsapp',
        value: 'Not Available',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Check Email',
        type: 'whatsapp',
        value: 'No',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Check Device',
        type: 'whatsapp',
        value: 'No',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Possible Migration',
        type: 'whatsapp',
        value: 'No',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Is Banned',
        type: 'whatsapp',
        value: 'No',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'FB Leak',
        type: 'whatsapp',
        value: 'Phone number +919997260627 not found in database',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'FB Leak Error',
        type: 'whatsapp',
        value: 'Not found',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'About History',
        type: 'whatsapp',
        value: 'धर्मो रक्षति रक्षितः',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'About History Set At',
        type: 'whatsapp',
        value: '2025-11-11T22:17:29.000Z',
        sourceOrType: 'type',
        category: 'TEXT',
      },
      {
        source: 'Instagram',
        type: 'platforms',
        value: 'Yes',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Snapchat',
        type: 'platforms',
        value: 'No',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Amazon',
        type: 'platforms',
        value: 'Yes',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        found: false,
        source: 'leakcheck',
        data: null,
        confidence: 0,
      },
      {
        source: 'Phone Number',
        type: 'hlr',
        value: '+919997260627',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Connectivity Status',
        type: 'hlr',
        value: 'CONNECTED',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Processing Status',
        type: 'hlr',
        value: 'COMPLETED',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Original Network',
        type: 'hlr',
        value: 'Airtel - Uttar Pradesh West',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Original Country',
        type: 'hlr',
        value: 'India',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Original Country Code',
        type: 'hlr',
        value: 'IN',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Original Country Prefix',
        type: 'hlr',
        value: '+91',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Is Ported',
        type: 'hlr',
        value: 'Yes',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Ported Network',
        type: 'hlr',
        value: 'Airtel - Karnataka',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Ported Country',
        type: 'hlr',
        value: 'India',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Ported Country Code',
        type: 'hlr',
        value: 'IN',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Ported Country Prefix',
        type: 'hlr',
        value: '+91',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Is Roaming',
        type: 'hlr',
        value: 'No',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'MCCMNC',
        type: 'hlr',
        value: '40445',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'MCC',
        type: 'hlr',
        value: '404',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'MNC',
        type: 'hlr',
        value: '45',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'MSC',
        type: 'hlr',
        value: 'MOBILE',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Cost',
        type: 'hlr',
        value: '0.005',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Timestamp',
        type: 'hlr',
        value: '2026-02-28 14:12:41.549+0530',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Data Source',
        type: 'hlr',
        value: 'MNP_DB',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Route',
        type: 'hlr',
        value: 'PTX',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Routing Instruction',
        type: 'hlr',
        value: 'AUTO:PTX:MNP_FALLBACK',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Storage',
        type: 'hlr',
        value: 'API-SYNC-2026-02',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        source: 'Lookup ID',
        type: 'hlr',
        value: '89a6333155be',
        sourceOrType: 'source',
        category: 'TEXT',
      },
      {
        found: false,
        source: 'aitan',
        data: null,
        confidence: 0,
      },
    ],
  },
};
